function [gammaTpH, gammaTmH] = dataIndependentStep(Obj, nData)
    ccVectors = ...
        computeRealSinusoidalCorrVector(nData, ...
        Obj.fullPitchGrid((Obj.dftRange(1,1):Obj.dftRange(1,2))+1)/...
        Obj.samplingFreq, Obj.maxPitchOrder);
    [gammaTpH, gammaTmH] = ...
        computeGamma(Obj.maxPitchOrder, Obj.dftRange, ccVectors);
end